### ISSUE TITLE
Deployment/update error map: map[] does not contain declared merge key: name

### ISSUE THREAD

**Issue by niekappartmedia** [Azure/k8s-deploy#10]
When i deploy the first time with k8s deploy everything works fine.
But when i deploy the second time i get the following error:

error calculating patch from openapi spec: map: map[] does not contain declared merge key: name

Strange though that when i deploy localy the firsttime with kubectl and update everything works fine.
But when k8s has deployed i even can not update with local kubectl i get the same error.

Any ideas what this could be?

This is the deployment yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      securityContext:
        runAsGroup: 33
        fsGroup: 33
      volumes:
        - name: nfs-bucket
          persistentVolumeClaim:
            claimName: nfs-bucket
      containers:
        - name: test
          image: niek/test:develop
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-bucket
              mountPath: "/var/www/bucket"
          envFrom:
            - secretRef:
                name: test-secret
          ports:
            - name: 80tcp01
              containerPort: 80
              protocol: TCP
          stdin: true
          tty: true
      imagePullSecrets:
        - name: dockerhub
```
