### ISSUE TITLE
Kubectl parse error

### ISSUE THREAD

**Issue by raphaelbernhart** [Azure/k8s-deploy#102]
Hello there,

I wanted to automate my deployments with github actions and to now it worked just fine. But now I came to the path where I have to deploy the manifest and there is an error. (https://github.com/raphaelbernhart/exchange/blob/master/.github/workflows/production.yml)

I get the error: ![Bildschirmfoto 2021-01-07 um 21 54 18](https://user-images.githubusercontent.com/48283236/103944313-bbbf7200-5133-11eb-9e91-2d21baa57aa4.png)

As I am understanding this message GoLang cannot parse the `apiVersion: v1` field. I am using a Rancher cluster as Kubernetes backend. I hope somebody can help me.

Repro steps:
- Github Deployment Action (azure/k8s-set-context@v1 + Azure/k8s-deploy@v1.3)

Current behaviour:
- Throwing an error while reading the kubeconfig file

Expected behaviour:
- Finish without an error.

**Comment by ds-ms** [comment]
@raphaelbernhart did you do something to resolve it? Perhaps if you could post how you resolved it, it would be helpful for any other user facing the same issue

**Comment by raphaelbernhart** [comment]
### **FIX**
The problem was that have understood the docs wrong. You have to parse the secret not the name of the secret. I thought the secret would be parsed by the service itself.

**wrong:**
```
- uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: KUBECONFIG
```

**right:**
```
- uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}
```
