### ISSUE TITLE
Option to ignore error from certificate auto signed

### ISSUE THREAD

**Issue by jbaojunior** [Azure/k8s-deploy#113]
I am trying to use the optional args to pass  `--insecure-skip-tls-verify` but this is not working. Has some way to do this?
```
    - uses: Azure/k8s-deploy@v1.3
      with:
        manifests: |
          /tmp/deployment.yaml
        images: deploy-service:${{ env.ENVIRONMENT }}
        args: '--insecure-skip-tls-verify=true'
```
