### ISSUE TITLE
Support different manifest delimiters

### ISSUE THREAD

**Issue by SamMousa** [Azure/k8s-deploy#126]
I'm working in an environment where I went to set the manifests dynamically.
Specifically I have an environment variable that contains the list of manifests, but passing this into the action does not work:

```yaml
      - name: Set manifests
        run: |
          echo 'MANIFESTS<<EOF' >> $GITHUB_ENV
          find k8s/shared k8s/staging -type f >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo "$MANIFESTS"
      - name: Authenticate to kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.STAGING_K8S_SECRET }}
      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'staging'
          manifests: |
            ${{ env.MANIFESTS }}
          images: |
            ghcr.io/herams-who/herams-backend/app:${{ github.sha }}
          kubectl-version: 'latest'      
```

There is no valid syntax that'll work here (afaik) because Github Actions will not properly put in multiline values here. 
This could be easily solved if a different separator would be accepted. 

Interestingly, current code splits by `\n`.
https://github.com/Azure/k8s-deploy/blob/main/src/run.ts#L62

```ts
 let manifests = manifestsInput.split('\n');
 ```

A clean solution would be to make the separator configurable as an input in the action. I can make a PR.
