### ISSUE TITLE
Image substitution only handles tag substitution

### ISSUE THREAD

**Issue by ggolub** [Azure/k8s-deploy#132]
This is more of an enhancement request than a bug (or perhaps a question if there is a workaround).

We are using terraform to create container registries with generated names.  Deployments with this action currently require that the the registry in the yaml is known.  That won't be the case in our scenario and we were expecting this action to be able to update the image name as well as the tag.  Example:

```
- name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1.2
        with:
          namespace: 'demo'
          manifests: |
            ./deploy/deployment.yaml
          images: |
            ${{env.REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
          imagepullsecrets: |
            demo-acr-secret
```
In my deployment.yaml:
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: mycontainerregistry.azurecr.io/demo
```

If the "REGISTRY_NAME" environment variable is set to "mycontainerregistry.azurecr.io" then the deployment works fine - the github.sha is used.  However, if another value is used then the deployment fails - the value from the .yaml file is used and the deployment fails.

This is very limiting.

**Comment by ds-ms** [comment]
I suppose you could solve that by generating your deployment.yaml files within the workflow. 
```yaml
run: | echo  "kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: ${{env.REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{github.sha}} " > temp.yml
```
And then use that temp.yml to deploy.

I agree that this is limiting, but it will also enforce that the change in docker image in production environment will always go through a PR.
