### ISSUE TITLE
What should be the image name in the deployment

### ISSUE THREAD

**Issue by mabroor007** [Azure/k8s-deploy#148]
What should be the specified image name in manifest/deployment.yml file as it is going to get replaced by the latest computed name. What should i put in place of the image
```
# Deployment for the app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
  labels:
    app: app-depl
spec:
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      name: app-pod
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-c
           image: *************
           ports:
            - containerPort: 3000
              name: port-c-port

```
what should i put in place of starts so that they get replaced by the new image link.
right now it says image name is invalid.
