### ISSUE TITLE
Use prefix for added annotations

### ISSUE THREAD

**Issue by stigok** [Azure/k8s-deploy#189]
It would be very helpful if the annotations applied with this action were prefixed, [as described in the Kubernetes annotations concept doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set).

> If the prefix is omitted, the annotation Key is presumed to be private to the user. Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add annotations to end-user objects must specify a prefix.

This would
- improve readability
- probably eliminate the chance of overwriting something already present
- know the origin of the annotations
- follow the guidelines of the Kubernetes concept documentation

My proposal is using the prefix `actions.github.com/<name>`.

This would mean that the following annotation:
```yaml
annotations:
  branch: refs/heads/main
  commit: 2c0ebf42424122a3690f7adac48e401ada43f8a9
  createdBy: stigok
  deployTimestamp: "1653392721857"
  jobName: deploy
  provider: GitHub
  repository: stigok/mydeploy
  run: "2377551111" 
  runUri: https://github.com/stigok/mydeploy/actions/runs/2377551111
  workflow: Continuous Deployment
```
would be replaced with
```yaml
annotations:
  actions.github.com/branch: refs/heads/main
  actions.github.com/commit: 2c0ebf42424122a3690f7adac48e401ada43f8a9
  actions.github.com/createdBy: stigok
  actions.github.com/deployTimestamp: "1653392721857"
  actions.github.com/jobName: deploy
  actions.github.com/provider: GitHub
  actions.github.com/repository: stigok/mydeploy
  actions.github.com/run: "2377551111" 
  actions.github.com/runUri: https://github.com/stigok/mydeploy/actions/runs/2377551111
  actions.github.com/workflow: Continuous Deployment
```

Somewhat related to https://github.com/Azure/k8s-deploy/issues/112, where the OP seems to have an issue with existing annotations being overwritten.
