### ISSUE TITLE
Annotating resources Error: HttpError: Bad credentials

### ISSUE THREAD

**Issue by januszj** [Azure/k8s-deploy#190]
In GitHub Enterprise Server 3.4.3 using self hosted runners.

My deployment works, pods are created and running filne, but the action fails with:

```yml
deployment "xx-api" successfully rolled out
Printing ingresses
/home/runner/actions-runner/_work/_tool/kubectl/1.24.1/x64/kubectl get ingress/ing-xxx-api -o json --insecure-skip-tls-verify --namespace ns-xxx-api
# ingres is printed here
...

Annotating resources
Error: HttpError: Bad credentials

```

My action looks like this:
```yml
          - name: Deploy application
            uses: Azure/k8s-deploy@v3.1
            with:
              action: deploy
              images: |
                  ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
              namespace: ${{ env.NAMESPACE }}
              manifests: ${{ steps.bake.outputs.manifestsBundle }}
```
