### ISSUE TITLE
Handling of unwanted characters in workflow name

### ISSUE THREAD

**Issue by jeliasson** [Azure/k8s-deploy#209]
I have an emoji (⚒️) in a workflow name and this causes errors when `Azure/k8s-deploy@v4.1` is done rolling out an deployment. Could we expose a option to optionally override the `workflowFriendlyName` name, or an option to allow filtering out unwanted characters?

**Error**
![image](https://user-images.githubusercontent.com/865493/177014979-e0b0880d-0982-42f0-a8cf-b2befdd3d43c.png)

**Workflow name**
![image](https://user-images.githubusercontent.com/865493/177014993-ac3b0b26-a915-4153-8448-34c5455009ee.png)

I tried setting the environment variable `GITHUB_WORKFLOW` but that did not do the trick.
```yml
- uses: Azure/k8s-deploy@v4.1
  with:
    [...]
  env:
    GITHUB_WORKFLOW: "foo"
```

Thanks!
