### ISSUE TITLE
Bug: Non-interactive authentication is required 

### ISSUE THREAD

**Issue by ealasgarov** [Azure/k8s-deploy#239]
### What happened?

When using k8s-deploy@v4, it is asking for non-interactive authentication:

asking me: "To sign in, use a web browser to open the page https://microsoft.com/devicelogin" and to authenticate with code, because of that the pipeline fails. Please see details in log attached below. 

Did anyone already encounter that before, if yes, what is a workaround?

This issue is also described here by me: https://stackoverflow.com/questions/73744666/aks-deployment-pipeline-azure-k8s-deployv4

### Version

- [X] I am using the latest version

### Runner

Self-hosted on AKS (running on the same AKS, to which I'm trying to deploy to)

### Relevant log output

```
Run Azure/k8s-deploy@v4
  with:
    action: deploy
    force: true
    strategy: basic
    namespace: actions-runner-system
    manifests: deployment.yaml
  
    images: ***.azurecr.io/github-runner-linux/github-runner-eph:latest
    pull-images: true
    route-method: service
    version-switch-buffer: 0
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    token: ***
    annotate-namespace: true
    private-cluster: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    KUBECONFIG: /runner/_work/_temp/kubeconfig_1663326539890


Deploying manifests
  /opt/hostedtoolcache/kubectl/1.25.1/x64/kubectl apply -f /tmp/deployment.yaml --force --insecure-skip-tls-verify --namespace *******
  W0916 11:09:01.696594    2327 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
  To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
  **To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code RG****Q to authenticate.**
  E0916 11:24:03.590914    2327 azure.go:162] Failed to acquire a token: failed acquiring new token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired

````

**Comment by OliverMKing** [comment]
Would you post the rest of your workflow? I'm curious about how you are setting your kubeconfig in particular.

k8s-deploy simply auths with the kubeconfig so it's likely an earlier step that's being done incorrectly.

**Comment by ealasgarov** [comment]
@OliverMKing 
I'm not sure about that, because it is working the same way on another cluster, something with the cluster perhaps might be set differently, but I can't figure out what it is. 
The pipeline for build and deploy:
```
name: build_deploy_aks
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**' 
      
jobs:
  build:
    runs-on: platform-aks-runner-noneph
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          tenant: ${{ secrets.TENANTID }}
          registry: ${{ secrets.REGISTRY }}
          git_access_token: ${{ secrets.GIT_ACCESS_TOKEN }} 
          repository: github-runner-linux
          #folder: ./
          #dockerfile: ./Dockerfile
          image:  github-runner-linux
          branch: main
          #tag: ${{ github.sha }}
          tag: latest
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}' 
          cluster-name: '${{ secrets.CLUSTER }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP }}' 
          name: '${{ secrets.CLUSTER }}'
          private-cluster: false 
          action: deploy
          force: true
          strategy: basic
          namespace: 'actions-runner-system'
          manifests: |
             lx-runner-deployment.yaml
          images: '${{ secrets.registry }}.azurecr.io/github-runner-linux/github-runner-linux:latest'
```
![image](https://user-images.githubusercontent.com/86415933/193272610-d69375b2-7f06-4aea-a74c-cd393dde5a84.png)
