### ISSUE TITLE
Bug: Promote operation for canary strategy doesn't work with v4.2 or later

### ISSUE THREAD

**Issue by parroty** [Azure/k8s-deploy#240]
### What happened?

Hi 👋 . I was testing the deployment scenario with `Canary` strategy, but the `promote` operation seems not working.
It just removes the `-canary` pods and it does not promote the original pods, which is similar behavior as `reject`.

### Observed Behaviors
- In my environment,
  - With `@v1.4` and `@v1.5`, deploy successfully promotes canary.
  - With `@v2.0` through `@v4.1`, deploy fails with different errors.
  - With `@v4.2` or later, deploy does not promote the canary.

### Implementations
I am wondering if #165 has some relationship with this behavior. I was trying to fix it, but I am struggling to overcome the errors due to the lack of knowledge around existing codebase. Do you have any insights? (including workaround, misconfiguration, etc.)

- "deploymentHelper" was removed and replaced with "deploy". But I assume it handles `deploy` rather than `promote`.
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL14
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL55
- I am not confident enough, but the behavior seems like the deploy logic tries to perform `deploy` operation at first (instead of `promote`, deploy `-baseline` and `-canary`, then remove the `-canary` as part of the clean-up). If it is true, it would not promote `-canary`.
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL61

### Additional Notes
- `Blue-Green` strategy is working as expected (`-green` pods will be promoted with the `promote` operation).

### Version

- [X] I am using the latest version

### Runner

ubuntu-latest

### Relevant log output

After deploying with Canary `strategy`, I can see the `-baseline` and `-canary` pods deployed along with original pods. I am expecting `-canary` pods to replace original pods after `promote` operation.

**Commands**

```shell
$ kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
ingress-nginx-controller-54d587fbc6-ssh82    1/1     Running   0          2d1h
nginx-deployment-6dc9c6cd6f-bdh77            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-fr59m            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-kkhnr            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-r7r42            1/1     Running   0          6h51m
nginx-deployment-baseline-78cfdc9fb6-vmxt4   1/1     Running   0          5h30m
nginx-deployment-canary-7c497564bb-lrnrb     1/1     Running   0          5h30m
```

```shell
$ kubectl get deploy
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
ingress-nginx-controller    1/1     1            1           2d1h
nginx-deployment            4/4     4            4           29h
nginx-deployment-baseline   1/1     1            1           5h31m
nginx-deployment-canary     1/1     1            1           5h31m
```

**Log with debug log enabled (Excerpt)**

During the "promote", the job tries `Creating canary and baseline objects` (which results in `unchanged` since they're already "deployed"), then `Deleting canary and baseline workloads` occurs.

```
Deploying input manifests
  ##[debug]Input manifest files: /tmp/Deployment_nginx-deployment_1662783396039,/tmp/Service_nginx_1662783396039,/tmp/Service_nginx-preview_1662783396040,/tmp/Ingress_nginx-ingress_1662783396040
  ::group::Deploying manifests

##[debug]Creating canary and baseline objects. Stable object found: 

deployment.apps/nginx-deployment-canary unchanged
deployment.apps/nginx-deployment-baseline configured
service/nginx unchanged
service/nginx-preview unchanged
ingress.networking.k8s.io/nginx-ingress unchanged
##[debug]Deployed manifest files: /tmp/Deployment_nginx-deployment-canary_1662783396511,/tmp/eployment_nginx-deployment-baseline_1662783396511,/tmp/Service_nginx_1662783396511,/tmp/Service_nginx-preview_1662783396511,/tmp/Ingress_nginx-ingress_1662783396511

Deleting canary and baseline workloads
##[debug]Kubectl run with command: /usr/local/bin/kubectl delete,Deployment,nginx-deployment-canary,--insecure-skip-tls-verify
/usr/local/bin/kubectl delete Deployment nginx-deployment-canary --insecure-skip-tls-verify
deployment.apps "nginx-deployment-canary" deleted
##[debug]Kubectl run with command: /usr/local/bin/kubectl delete,Deployment,nginx-deployment-baseline,--insecure-skip-tls-verify
/usr/local/bin/kubectl delete Deployment nginx-deployment-baseline --insecure-skip-tls-verify
deployment.apps "nginx-deployment-baseline" deleted
::endgroup::
```

**Workflow**

```yaml
name: Deploy (Canary)
on:
  workflow_dispatch:
env:
  RESOURCE_GROUP: xxx
  AKS_CLUSTER_NAME: xxx
  SECRET: xxx
  APP_NAME: xxx
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.xxx }}
        username: ${{ secrets.yyy }}
        password: ${{ secrets.zzz }}
    - run: |
        docker build . -t ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
      working-directory: ./xxx
  deployapp:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - uses: actions/checkout@v3
      - name: Set cluster context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.aaa }}'
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - uses: azure/k8s-create-secret@v1
        name: Create image pull secret
        with:
          container-registry-url: ${{ secrets.xxx }}
          container-registry-username: ${{ secrets.yyy }}
          container-registry-password: ${{ secrets.zzz }}
          namespace: default
          secret-name: ${{ env.SECRET }}
          arguments: --force true
      - name: Deploy app
        uses: k8s-deploy/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: deploy
          percentage: 25
  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: akspromotion
    steps:
      - run: echo asked for approval
  promotereject:
    if: always()
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3
      - name: Set cluster context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.aaa }}'
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: Promote App
        uses: azure/k8s-deploy@v4
        if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: promote
          percentage: 25
      - name: Reject App
        uses: azure/k8s-deploy@v4
        if: ${{ env.WORKFLOW_CONCLUSION != 'success' }}
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: reject
          percentage: 25
```
