### ISSUE TITLE
Feature Request: CroJobs

### ISSUE THREAD

**Issue by juzerali** [Azure/k8s-deploy#243]
### Feature request

Requesting support for CronJobs. Currently image substitution in CronJobs does not work.

```yml
  deploy:
    name: Deploy
    needs: [ build, publish ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://my-kube-domain
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kube/cronjob.yml
          images: |
            asia-south1-docker.pkg.dev/project/repo/image:${{ github.sha }}
```

Expected: CronJob is updated with the new image as per `${{ github.sha }}`
Actual: Image name that is hardcoded, gets updated
