### ISSUE TITLE
Bug: private cluster action success on error

### ISSUE THREAD

**Issue by y-luis-rojo** [Azure/k8s-deploy#244]
### What happened?

The execution of Azure/k8s-deploy@v4 action shows an error, nothing is deployed and still the result of the job is a success:
![image](https://user-images.githubusercontent.com/8008773/195102649-ddf0b941-050d-4e96-a53d-f465b8544f89.png)

I would expect any execution error result in a job failure.

### Version

- [X] I am using the latest version

### Runner

self-hosted Ubuntu 20.04

### Relevant log output

Sorry, don't know how to run in debug mode, please share how to do it, if needed.

**Comment by OliverMKing** [comment]
Hello @y-luis-rojo! Thanks for the issue. Could you post what your workflow looks like please?

**Comment by y-luis-rojo** [comment]
Sure:
```
  deploy:
    runs-on: [ atc-ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        id: install
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - run: az acr login -n ${{ env.CONTAINER_REGISTRY }}
      - uses: Azure/k8s-deploy@v4
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
          private-cluster: true
          resource-group: ${{ env.RESOURCE_GROUP }}
          name: ${{ env.CLUSTER_NAME }}
```
