### ISSUE TITLE
Bug: deployment.apps not found even though the deployment exists

### ISSUE THREAD

**Issue by a-z-i-z** [Azure/k8s-deploy#256]
### What happened?

The action uses a deployment file and it successfully deploys the application. But when it goes to check the status of deployment (Checking manifest stability), it throws "Error from server (NotFound): deployments.apps "test-deployment" not found.

I had used this action before and was working well. Not sure how but suddenly I started receiving this error.
Below is the configuration,
```YAML
- name: Deploy to AKS
  uses: Azure/k8s-deploy@v4.6
  with:
    resource-group: ${{ env.AKS_RESOURCE_GROUP_NAME }}
    name: ${{ env.AKS_CLUSTER_NAME }}
    action: deploy
    namespace: 'default'
    manifests: .k8s/test-deployment.yml
    images: ${{ env.REGISTRY_NAME }}.azurecr.io/test-repo:${{ github.sha }}
    private-cluster: true
    annotate-namespace: false
```

### Version

- [X] I am using the latest version

### Runner

GitHub hosted runner

### Relevant log output

![image](https://user-images.githubusercontent.com/58370459/200846082-7b0d1826-4fd0-49d0-98d7-3784efdc13c6.png)
