### ISSUE TITLE
imagePullSecret becomes the image

### ISSUE THREAD

**Issue by jeliasson** [Azure/k8s-deploy#26]
Hi,

I'm not sure, but I think commit 1cae8dfe8b6485cf29c5699565ba557165b600b0 broke some things on `Azure/k8s-deploy@v1`. Basically the generated Kubernetes manifest seem to have wrong  `imagePullSecret` value. Instead of the image pull secret, it's the `image` value.

This is what I see in the deployed manifest in Kubernetes (the actual deployed). 
```
image: cr.example.com/sydnod-ci
imagePullSecrets:
  - name: 'cr.example.com/sydnod-ci:web-dev-20200305-<retracted>'
```
*This is where I expect* `imagePullSecret` *to contain* `sydnod-ci-container-registry` *and not* `cr.example.com/sydnod-ci:web-dev-20200305-<retracted>`.

Creation of registery secret
```
Run Azure/k8s-create-secret@v1
/usr/bin/kubectl create secret docker-registry sydnod-ci-container-registry --docker-username *** --docker-password *** --docker-server *** --docker-email   -n sydnod-ci
secret/sydnod-ci-container-registry created
```

Deployment to Kubernetes
```
Run Azure/k8s-deploy@v1
  with:
    namespace: sydnod-ci
    manifests: ./manifests.yaml
    images: ***/sydnod-ci:web-dev-20200305-<retracted>
    imagepullsecrets: sydnod-ci-container-registry
 
    strategy: none
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    action: deploy
```

Hope anyone can shred some light on this issue.

Thanks!
