### ISSUE TITLE
Error: TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by 63isOK** [Azure/k8s-deploy#266]
### What happened?

my workflow:
```yaml
      - name: "deploy"
        uses: Azure/k8s-deploy@v4.7
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          namespace: ${{ env.NAMESPACE }}
          # Path to the manifest files which will be used for deployment.
          manifests: ${{ env.YAML_DIR }}
          # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git-tag.outputs.tag }}
          pull-images: true
          imagepullsecrets: docker-login
          # deploy, promote, or reject
          action: deploy
          # Deploy when a previous deployment already exists. If true then --force argument is added to the apply command
          force: true
```

there is an error `[error]TypeError: Cannot read properties of null (reading '0')` after `annotated`.

no `try-catch` in function annotateResources:

```ts
   for (const file of files) {
      try {
         const annotateResult = await kubectl.annotateFiles(
            file,
            annotationKeyValStr
         )
         annotateResults.push(annotateResult)
      } catch (e) {
         core.warning(`failed to annotate resource: ${e}`)
      }
   }

   for (const resource of resourceTypes) {
      if (
         resource.type.toLowerCase() !==
         models.KubernetesWorkload.POD.toLowerCase()
      ) {
         ;(
            await annotateChildPods(
               kubectl,
               resource.type,
               resource.name,
               annotationKeyValStr,
               allPods
            )
         ).forEach((execResult) => annotateResults.push(execResult))
      }
   }
```

### Version

- [X] I am using the latest version

### Runner

github action + k8s v1.25.4

### Relevant log output

2022-12-04T13:52:38.0853062Z ##[group]Run Azure/k8s-deploy@v4.7
2022-12-04T13:52:38.0863628Z ##[endgroup]
2022-12-04T13:52:38.1995713Z ##[group]Deploying manifests
2022-12-04T13:52:38.2022607Z [command]/usr/local/bin/kubectl apply -f /tmp/Deployment_hello_1670161958196,/tmp/Ingress_hello-ingress_1670161958196,/tmp/Namespace_hello_1670161958197,/tmp/Service_hello_1670161958197 --force --namespace hello
2022-12-04T13:52:41.9320472Z deployment.apps/hello configured
2022-12-04T13:52:42.1766322Z ingress.networking.k8s.io/hello-ingress unchanged
2022-12-04T13:52:42.4237082Z namespace/hello unchanged
2022-12-04T13:52:42.6698221Z service/hello unchanged
2022-12-04T13:52:42.6739867Z ##[endgroup]
2022-12-04T13:52:42.6740588Z ##[group]Checking manifest stability
2022-12-04T13:52:42.6759585Z [command]/usr/local/bin/kubectl rollout status Deployment/hello --namespace hello
2022-12-04T13:52:44.4079784Z Waiting for deployment "hello" rollout to finish: 1 old replicas are pending termination...
2022-12-04T13:54:02.3545192Z Waiting for deployment "hello" rollout to finish: 1 old replicas are pending termination...
2022-12-04T13:54:02.3956312Z deployment "hello" successfully rolled out
2022-12-04T13:54:02.3990113Z ##[endgroup]
2022-12-04T13:54:02.3993021Z ##[group]Printing ingresses
2022-12-04T13:54:02.4009992Z [command]/usr/local/bin/kubectl get ingress/hello-ingress -o json --namespace hello
2022-12-04T13:54:03.1783242Z ##[endgroup]
2022-12-04T13:54:03.1786032Z ##[group]Annotating resources
2022-12-04T13:54:06.3182719Z [command]/usr/local/bin/kubectl annotate namespace hello actions.github.com/k8s-deploy=
2022-12-04T13:54:08.0540007Z namespace/hello annotated
2022-12-04T13:54:08.0565766Z [command]/usr/local/bin/kubectl annotate -f /tmp/Deployment_hello_1670161958196 actions.github.com/k8s-deploy=
2022-12-04T13:54:10.1379583Z deployment.apps/hello annotated
2022-12-04T13:54:10.1406969Z [command]/usr/local/bin/kubectl annotate -f /tmp/Ingress_hello-ingress_1670161958196 actions.github.com/k8s-deploy=
2022-12-04T13:54:11.0919957Z ingress.networking.k8s.io/hello-ingress annotated
2022-12-04T13:54:11.0957808Z [command]/usr/local/bin/kubectl annotate -f /tmp/Namespace_hello_1670161958197 actions.github.com/k8s-deploy=
2022-12-04T13:54:12.8102623Z namespace/hello annotated
2022-12-04T13:54:12.8125267Z [command]/usr/local/bin/kubectl annotate -f /tmp/Service_hello_1670161958197 actions.github.com/k8s-deploy=
2022-12-04T13:54:13.7816438Z service/hello annotated
2022-12-04T13:54:15.8375745Z ##[error]TypeError: Cannot read properties of null (reading '0')
2022-12-04T13:54:15.8463831Z Post job cleanup.
2022-12-04T13:54:15.9122752Z ##[group]Removing temp folder /tmp/docker-build-push-uhPZTa
