### ISSUE TITLE
Bug: Unable to get config, even after using `k8s-set-context`

### ISSUE THREAD

**Issue by pilotkid** [Azure/k8s-deploy#280]
### What happened?

Unable to successfully authenticate cluster 

`KUBE_CONFIG` has been validated by using the following command

```yaml
- uses: actions-hub/kubectl@master
  env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  with:
    args: get pods
```

The workflow file is as follows

```yaml

name: Deploy test site
on:
  push:
    branches:
      - master
  workflow_dispatch:      
jobs:
  build-and-deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Validate KUBE_CONFIG
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_IP }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_KEY }}

      - name: Build Docker container
        run: docker build --pull --rm -f "dockerfile" -t shooter-api:latest "."

      - name: Push Image To Registry
        run: |
          docker tag shooter-api:latest ${{ secrets.REGISTRY_IP }}/straight-score/shooter-api:${{ github.sha }}
          docker push ${{ secrets:REGISTRY_IP }}/straight-score/shooter-api:${{ github.sha }}
     
      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          strategy: basic
          namespace: 'default'
          manifests: |
              kube/next
          images: '${{ secrets.HARBOR_REGISTRY_IP }}/straight-score/shooter-api:${{ github.sha }}'
          force: true
```

### Version

- [X] I am using the latest version

### Runner

Github Ubuntu-latest

### Relevant log output

```txt
Run Azure/k8s-deploy@v4
Unexpected error attempting to determine if executable file exists '/usr/local/bin/kubectl/kubectl': Error: ENOTDIR: not a directory, stat '/usr/local/bin/kubectl/kubectl'
Deploying manifests
  /opt/hostedtoolcache/kubectl/1.26.1/x64/kubectl apply -f /tmp/deployment.yaml,/tmp/ingress.yaml,/tmp/service.yaml --force --namespace default
  error: error loading config file "/home/runner/work/_temp/kubeconfig_167635718[23](https://github.com/Straight-Score/shooter-api/actions/runs/4171189337/jobs/7220872590#step:13:24)89": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
  Error: Error: undefined
```

**Comment by OliverMKing** [comment]
@pilotkid can you try again with bumping `azure/setup-kubectl` and `azure/k8s-set-context` to `v3`? 

Based on the error message, it looks like your Kubeconfig is unable to be parsed correctly. I wonder if it is in a different format. Could you post the general format of your Kubeconfig (with the important information redacted)?

**Comment by ejaifeobuks** [comment]
Hi @pilotkid, thanks for the report!

The key error — `cannot unmarshal string into Go value of type struct {...}` — means `kubectl` got your kubeconfig as a plain string it couldn't parse. This is almost certainly a **format mismatch**: `actions-hub/kubectl` expects `KUBE_CONFIG` to be **base64-encoded** (so your validation step passes), but `Azure/k8s-set-context` expects the **raw, plain-text** kubeconfig YAML.

**Fix:** pass the decoded, plain-text kubeconfig to `k8s-set-context`, and bump your actions to their latest versions:

```yaml
- uses: Azure/k8s-set-context@v4
  with:
    method: kubeconfig
    kubeconfig: ${{ secrets.KUBE_CONFIG }}   # raw kubeconfig YAML, not base64
```

Since this looks like a config issue rather than a bug, **I'll close it for now** — please feel free to **reopen** if you're still stuck after trying the above. 🙂
