### ISSUE TITLE
Bug: Image is not being replaced in the manifest

### ISSUE THREAD

**Issue by andresguisado** [Azure/k8s-deploy#286]
### What happened?

**Context:**

Configured k8s-deploy@v4 gitub action as follow:

https://github.com/aquasaemea/insecure-bank-app-andres/blob/main/.github/workflows/aquasec.yml#L151

IMAGE_TAG is an env var defined at the beginning of the pipeline and it is getting the value from the "github run number id":

https://github.com/aquasaemea/insecure-bank-app-andres/blob/main/.github/workflows/aquasec.yml#L14

Github action pipeline: 

https://github.com/aquasaemea/insecure-bank-app-andres/actions/runs/4961516330/jobs/8878467758

**Problem:**
The image defined in k8s-deploy@v4 job should be replaced the image in the following k8s manifest changing the tag latest to "github run id" but it doesn't work and it always deploys with  the "latest" tag as it is in the manifest:

https://github.com/aquasaemea/insecure-bank-app-andres/blob/main/manifests/dev/deployment.yaml#L26

### Version

- [X] I am using the latest version

### Runner

Github runners

### Relevant log output

I didn't find in the documentation how to run this in debug mode:

https://github.com/marketplace/actions/deploy-to-kubernetes-cluster

**Comment by OliverMKing** [comment]
Hello! I'll look into this. You may want to consider [artifact-substitute](https://github.com/Azure/k8s-artifact-substitute) as a workaround.

**Comment by OliverMKing** [comment]
Hello @andresguisado. I don't believe supported by GitHub Workflows in general (not k8s-deploy specific).

Here's a [related thread](https://github.com/orgs/community/discussions/26529).

Try this
```yaml
      - name: Deploying to Dev
        uses: azure/k8s-deploy@v4 
        with:
           namespace: ag-dev
           images: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}'
           manifests: |
              manifests/dev/deployment.yaml
              manifests/dev/service.yaml
```
