### ISSUE TITLE
using `azure/k8s-deploy@v1` errors

### ISSUE THREAD

**Issue by bpowell** [Azure/k8s-deploy#30]
configuration:
```
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            deploy/deployment.yaml
          namespace: 'bpowell'
          images: |
            myapp.azurecr.io/kube-notify:${{ steps.get_image_tag.outputs.image_tag }}
```

the deployment.yaml contents:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-notify-deployment
spec:
  selector:
    matchLabels:
      app: kube-notify
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-notify
    spec:
      containers:
      - name: kube-notify
        image: myapp.azurecr.io/kube-notify
```

error message:
```
Run azure/k8s-deploy@v1
  with:
    manifests: deploy/deployment.yaml
  
    namespace: bpowell
    images: ***.azurecr.io/kube-notify:20200416-35db60a
  
    strategy: none
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    action: deploy
  env:
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_******
    AZURE_HTTP_USER_AGENT: 
strategy:  none
##[error]TypeError: Cannot read property 'trim' of undefined
```

**Comment by ds-ms** [comment]
Curious, don't you need to mount your imagepullsecrets for accessing the image from your acr?  or did you make it public?

**Comment by bpowell** [comment]
when not using github actions to do the deployment it works just fine. i didn't think i needed to configure anything different.

**Comment by ds-ms** [comment]
No no, you don't. I was just curious as to how you've configured. 
This seems like a code-defect. I'll take a look.

**Comment by bpowell** [comment]
trying out `k8s-deploy@master` i get a totally different error

```
Run azure/k8s-deploy@master
  with:
    manifests: deploy/deployment.yaml
  
    namespace: brandon
    images: ***.azurecr.io/kube-notify:20200417-6f62e6f
  
    strategy: none
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    action: deploy
  env:
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_******
    AZURE_HTTP_USER_AGENT: 
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/tool-cache'
Require stack:
- /home/runner/work/_actions/azure/k8s-deploy/master/lib/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/k8s-deploy/master/lib/run.js:12:19)

```

this is with the same configuration above, just different version of the action

**Comment by ds-ms** [comment]
`master` doesn't have `node_modules` so you can't use it in your deployments

**Comment by bpowell** [comment]
okay that makes sense! have you been able to replicate the error? looking through the code on the `v1` tag, it looks like nothing should fail with a `.trim()`

**Comment by ds-ms** [comment]
@rgsubh to take a look.

**Comment by rgsubh** [comment]
Hello @bpowell Can you please let me know if your are still facing this issue? if so can you share your full configuration file. I was not able to recreate the "Cannot read property 'trim' of undefined" even after a few try's.

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if it's still happening

**Comment by enzoqtvf** [comment]
@ds-ms Hey, I'm getting the same issue.
Here is the place where I sue it in my action:
```
- name: Deploy to kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment/dev/deployment.yml
        images: some registry/omega:sometag
```

And I get the exact same issue:
```
Run azure/k8s-deploy@v1
  with:
    manifests: deployment/dev/deployment.yml
    images: some registry/omega:sometag
    strategy: none
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    action: deploy
    force: false
  env:
    some env
strategy:  none
##[error]TypeError: Cannot read property 'trim' of undefined
```

I've also been trying using some examples from the read me but get same error :/
