### ISSUE TITLE
k8s-deploy does not update pods with new images

### ISSUE THREAD

**Issue by Chris-Sheridan** [Azure/k8s-deploy#314]
### What happened?

This executes as part of my GH Actions after a code update.  The resulting image builds fine and is uploaded to my ACR registry.  GH Actions successfully runs k8s-deploy as part of the workflow, but it doesn't detect any changes.  The pods never bleed over and the old pods still run.  I'm sure I have something wrong but I've had no luck searching.

Here's my action...
      - name: Deploy Cluster
        uses: Azure/k8s-deploy@v4
        with:
          resource-group: $RESOURCE_GROUP
          name: $NAME
          action: deploy
          strategy: basic
          pull-images: false
          namespace: ingress-basic
          private-cluster: false
          manifests: |
              k8s/deployment.yaml
              k8s/service.yaml
              k8s/cluster-issuer.yaml
              k8s/ingress.yaml
          images: |
              myacr.azurecr.io/my-app:latest

I appreciate any thoughts people have on what I'm missing.

### Version

- [X] I am using the latest version

### Runner

self-hosted, Azure ACA Container Job

### Relevant log output

  /usr/local/bin/kubectl apply -f /tmp/deployment.yaml,/tmp/service.yaml,/tmp/cluster-issuer.yaml,/tmp/ingress.yaml --namespace ingress-basic
  deployment.apps/my-app unchanged
  service/my-app unchanged
  clusterissuer.cert-manager.io/letsencrypt unchanged
  ingress.networking.k8s.io/my-app-ingress unchanged

**Comment by OrellBuehler** [comment]
If you use `latest` as the tag for all images and you don't set `pull-images` to `true`, then I believe it will use the cached images instead of updating them from your registry.

**Comment by leonardlin** [comment]
I encountered the same symptom.

I use unique tags for docker images not "latest"

Example: app:<hash>
"pull-images" is left to default "true".
In the logs I can see it does a test pull before deployment with the correct updated image-tag.

However nothing actually gets updated.
The old pods still keep running.

````
        uses: Azure/k8s-deploy@v5
        with:
          resource-group: company-prod-northeurope
          name: clusterName
          action: deploy
          strategy: basic
          namespace: namespaceName
          manifests: ./devops/k8s-deployment.yaml
          images: companyname.azurecr.io/app:safdsafdsafdsfd
````
