### ISSUE TITLE
Bug: Deploy Manifest from URL not working

### ISSUE THREAD

**Issue by tpcgold** [Azure/k8s-deploy#328]
### What happened?

Deployment of a Manifest form a URL is not working correctly. e.g.:
``` 
      - name: Deploy Cert-Manager to AKS
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
          namespace: cert-manager
          action: deploy
```

### Version

- [X] I am using the latest version

### Runner

GitHub Hosted in Private VNET Azure

### Relevant log output

Run Azure/k8s-deploy@v5
  with:
    manifests: https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
  
    namespace: cert-manager
    action: deploy
    pull-images: true
    strategy: basic
    route-method: service
    version-switch-buffer: 0
    traffic-split-method: pod
    percentage: 0
    force: false
    token: ***
    annotate-resources: true
    annotate-namespace: true
    private-cluster: false
    skip-tls-verify: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_17[2](https://github.com/prosperity-tech/k8s-azure-IaC-OPS/actions/runs/10488441119/job/29050948994#step:6:2)4237444055
    KUBE_CONFIG_PATH: /home/runner/work/_temp/kubeconfig_17242[3](https://github.com/prosperity-tech/k8s-azure-IaC-OPS/actions/runs/10488441119/job/29050948994#step:6:3)7444055
Error: Error: Exception occurred while reading the file https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml: Error: encountered error trying to pull YAML from URL https://github.com/cert-manager/cert-manager/releases/download/v1.1[5](https://github.com/prosperity-tech/k8s-azure-IaC-OPS/actions/runs/10488441119/job/29050948994#step:6:5).3/cert-manager.yaml: failed to parse manifest from url https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml: no objects detected in manifest
