### ISSUE TITLE
Variable as Namespace

### ISSUE THREAD

**Issue by hikarukujo** [Azure/k8s-deploy#45]
Maybe I'm missing something simple, but I cannot figure this out for the life of me. I'm trying to set the namespace to dev if the branch is not "master" and I have the branch detection working right now. But it looks like k8s-deploy will not take a variable as the namespace name. Maybe it's a syntax error I'm missing? Here is my yaml:

```
on:
  push:
    branches:
    - dev
    - master

name: CI/CD Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/revio-calendar-backend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/revio-calendar-backend:${{ github.sha }}

        - name: 'Set context for AKS'
          uses: Azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            cluster-name: ${{ secrets.CLUSTER_NAME }}
            resource-group: ${{ secrets.RESOURCE_GROUP }}

        - name: 'Create AKS Secret'
          uses: Azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: c1-k8s-secret

        - name: 'Set Dev Branch'
          env:
            NAMESPACE: dev
          run: echo "$NAMESPACE"
            
        - name: 'Set Master Branch'
          if: endsWith(github.ref, '/master')
          env:
            NAMESPACE: prod
          run: echo "$NAMESPACE"
    
        - name: 'Deploy to Kubernetes'
          uses: Azure/k8s-deploy@v1
          with:
            namespace: $NAMESPACE
            manifests: |
              manifests/deployment.yml
              manifests/service.yml
            images: |
              ${{ secrets.REGISTRY_LOGIN_SERVER }}/revio-calendar-backend:${{ github.sha }}
            imagepullsecrets: |
              c1-k8s-secret
```

I succeed on all steps but the last, which says it cannot find a namespace named "$NAMEPSACE":

> Error from server (NotFound): error when creating "/tmp/Service_revio-calendar-backend_1592439878791": namespaces "$NAMESPACE" not found

Is there a way to use a variable to determine the namespace so I can avoid one yaml for master and one for other branches?
