### ISSUE TITLE
Possibility to inform environment variable to be replaced in the container

### ISSUE THREAD

**Issue by joseotavioq** [Azure/k8s-deploy#72]
As we already have the option to change the container name (images).
It would be nice if we have an option to change the environment variable values for containers.

**Example of a YAML for Kubernetes**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mycontainer
          image: myregistry\mycontainer:v1
          ports:
            - containerPort: 80
          env:
            - name: MY_CONTAINER_ENV
              value: X
```

**Example of a Github Action:**
```
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes.yaml
          env: |
            MY_CONTAINER_ENV: "${{ secrets.MY_CONTAINER_ENV }}"
```

**Comment by koushdey** [comment]
@pulkitaggarwl Can you have a look at it?

**Comment by koushdey** [comment]
@joseotavioq You can add custom env variables as part of a workflow. If you wish to change the value for an env var before an action run then either you can have different values for your env var in separate steps or have a dedicated env var for the action.

I am trying to understand a use-case for this request to be added in the action.

**Comment by joseotavioq** [comment]
@koushdey I want to add an env variable as a parameter for a container when it starts.
To do that, I need to specify in the Kubernetes YAML file the value of that variable. (As you can see in the example above "MY_CONTAINER_ENV").
But, in my case I want to use a GitHub Secret as a value of that env variable in the YAML file. For this reason, I need to replace the value I have in the YAML file for the value I have in GitHub Secrets.

`MY_CONTAINER_ENV: "${{ secrets.MY_CONTAINER_ENV }}"`

**Comment by ds-ms** [comment]
@josetavioq Have you considered using helm for the same? You could use `helm` to replace tokens and in turn using `azure/k8s-bake` action convert your helm chart to raw manifests and pipe it to `k8s-deploy` action.

Here's some documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/bake?view=azure-devops 

Although the documentation talks about usage in ADO environment, we followed the same concepts in our https://github.com/azure/k8s-bake action.

**Comment by joseotavioq** [comment]
@ds-ms Helm no, but I use another task to replace the env, as you can see below.

```
    - name: YAML Transform - MY_CONTAINER_ENV
      uses: jwsi/secret-parser@v1
      with:
        filename: kubernetes.yaml
        secret-name: MY_CONTAINER_ENV
        secret-value: ${{ secrets.MY_CONTAINER_ENV }}
```
As I said, it would be nice if we have an option in this task, to avoid use another task to do a simple replace.
