### ISSUE TITLE
Wildcards for manifest files are not supported although readme explicitly says so...

### ISSUE THREAD

**Issue by Hades32** [Azure/k8s-deploy#9]
This doesn't work, with a file not found error:
```
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: 'k8s/*.yaml'
        images: |
          bla/da-image:${{ github.sha }}
```
But this does:

```
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: 'k8s/deploy.yaml'
        images: |
          bla/da-image:${{ github.sha }}
```
otherwise great action, but this is really strange...
